name: 'Recovery Compiler For Github Actions' 
author: 'ElytrA8' 
description: 'Universal Recovery Compiler'

runs:
  using: "composite"
  steps:
    - run: curl -sL https://raw.githubusercontent.com/Carbonatedblack/Recovery-Compiler/beta/prepare.sh | bash
      shell: bash
    - run: curl -sL https://raw.githubusercontent.com/Carbonatedblack/Recovery-Compiler/beta/builder.sh | bash
      shell: bash
branding:
  icon: 'box'
  color: 'black'
